### ISSUE TITLE
HUD broken on edge. 

### ISSUE THREAD

**Issue by mike-kaufman** [Glimpse/Glimpse.Client.Hud#14]
**Repro:**
  1.  launch express.test.app
  2.  navigate to http://localhost:3000/
  3. click on HUD in bottom of page to open glimpse
  
 **Expected:**
glimpse will open 

 **Actual:**
nothing happens.

May be related to chagne of the target of the href from _blank to _glimpse.

**Comment by avanderhoorn** [comment]
So in testing, it looks like if you close all edge windows and then click the "g" things work fine. If you then go back to your original page again and click on "g" again, Edge doesn't steal focus on the window that was already opened. But if you then close Glimpse so that you are back to 1 window again, and click the "g" it will open again. @mike-kaufman can you confirm that this is what you have seen?

**Comment by mike-kaufman** [comment]
OK, I think you're right.  I still see some pretty sluggish behavior on edge, but we have another issue open for that.

**Comment by avanderhoorn** [comment]
@nikmd23 are we ok with this behaviour for M017?

**Comment by nikmd23** [comment]
> @nikmd23 are we ok with this behaviour for M017?

There's nothing we can do to fix it really.
