### ISSUE TITLE
[HUD] Restyle HUD to match designs

### ISSUE THREAD

**Issue by mike-kaufman** [Glimpse/Glimpse.Client.Hud#17]
- Get Mock from Chet
   - Implement new styling.
   - Make unnecessary HUD cells invisible. 
  - latest design: https://github.com/Glimpse/Glimpse.Design/blob/master/%5BLatest%5D%20HUD.md

**Comment by legomushroom** [comment]
We can get `good` browsers support for `translucent background` with `SVG filters` fallback but last time I've checked(roughly a year ago) browsers had big performance issues `paining` blurred elements(better for `CSS filters`, worse for `SVG filters`). Furthermore, having the `HUD` fixed above a page will probably cause `paint storms` to occur bogging down the performance of the page it is running on. To prevent `paint-storms` we will need to apply some workarounds, for instance, sending the `HUD` to it's own `composite layer` -- and this can cause even more performance problems due to `CPU->GPU` load `bottleneck` (we will have to paint on `CPU` and `only then` load to `GPU` on every `paint`).

Just wanted to point out this `rendering performance` concerns. We can probably implement it `translucent`, test it out performance wise and if something wrong, `fallback` to `semi-transparent` background instead.

**Comment by chetsangnil** [comment]
Thx @legomushroom for the input, ur plan makes a lot of sense to me!

**Comment by davidkpiano** [comment]
@mike-kaufman How extensive should the changes done here be? I can modify the styling so that it matches the mocks; however, there is a lot of code that is no longer necessary (i.e., it can be refactored out). My plan is to just take care of styling at face-value in this PR, and probably refactor the HUD in the future, based on upcoming designs. Does that sound about right?

**Comment by mike-kaufman** [comment]
> My plan is to just take care of styling at face-value in this PR, and probably refactor the HUD in the future, based on upcoming designs. 

@davidkpiano  - Please do the styling updates, and then update the HUD to only show the "view full glimpse" and "total time" sections as shown in the mocks.  At this point, don't delete code - either comment stuff out or make the undesired cells invisible - whichever is easier.  The goal is to eventually bring these additional cells back, we just need a bit more thought on what they should be under different circumstances.  When we have a clear plan on that, it will be more clear about whether existing code can be used as-is, re-written, or deleted.

**Comment by nikmd23** [comment]
This is now available in Glimpse for Node 0.18.9. Please see our [announcement issue](https://github.com/Glimpse/Home/issues/93) for more information.
